version: '3.8'

services:
  app-react:
      container_name: frontend_tutora
      image: jessicamartins/app-react-tutora
      ports:
          - '8080:3000'
      depends_on:
        - app-node

  app-node:
    container_name: backend_tutora
    image: jessicamartins/app-node-tutora
    ports:
      - '5000:5000'